const whereConst = {
  common: {
    EQUALS: "EQUALS",
    NOT_EQUALS: "NOT_EQUALS",
    IS_EMPTY: "IS_EMPTY",
    IS_NULL: "IS_NULL",
    IS_NOT_EMPTY: "IS_NOT_EMPTY",
    IS_NOT_NULL: "IS_NOT_NULL",
    IS_ANY: "IS_ANY",
    IS_NOT_ANY: "IS_NOT_ANY",
  },
  string: {
    CONTAINS: "CONTAINS",
    STARTS_WITH: "STARTS_WITH",
    ENDS_WITH: "ENDS_WITH",
    NOT_CONTAINS: "NOT_CONTAINS",
    NOT_STARTS_WITH: "NOT_STARTS_WITH",
    NOT_ENDS_WITH: "NOT_ENDS_WITH",
  },
  number: {
    GREATER_THAN: "GREATER_THAN",
    LESSER_THAN: "LESSER_THAN",
    GREATER_THAN_EQUALS: "GREATER_THAN_EQUALS",
    LESSER_THAN_EQUALS: "LESSER_THAN_EQUALS",
  },
  date: {
    GREATER_THAN: "GREATER_THAN",
    LESSER_THAN: "LESSER_THAN",
    GREATER_THAN_EQUALS: "GREATER_THAN_EQUALS",
    LESSER_THAN_EQUALS: "LESSER_THAN_EQUALS",
  },
};

export default whereConst;
