export const TEST_SUCCESS = "TEST_SUCCESS";
export const TEST_FAILURE = "TEST_FAILURE";
export const RESET_TEST = "RESET_TEST";
export const SELECT_LAYOUT = "SELECT_LAYOUT";
export const REMOVE_COMPONENT = "REMOVE_COMPONENT";
export const SET_ACTIVE_BOX = "SET_ACTIVE_BOX";
export const SET_SELECTED_COMPONENT_PATH = "SET_SELECTED_COMPONENT_PATH";
export const ADD_COMPONENT = "ADD_COMPONENT";