export const TEST_SUCCESS = "TEST_SUCCESS";
export const TEST_FAILURE = "TEST_FAILURE";
export const RESET_TEST = "RESET_TEST";
export const SELECT_LAYOUT = "SELECT_LAYOUT";
export const REMOVE_COMPONENT = "REMOVE_COMPONENT";
export const SET_ACTIVE_BOX = "SET_ACTIVE_BOX";
export const SET_SELECTED_COMPONENT_PATH = "SET_SELECTED_COMPONENT_PATH";
export const ADD_COMPONENT = "ADD_COMPONENT";
export const SET_PROPS_COMPONENT_PATH = "SET_PROPS_COMPONENT_PATH";
export const TOGGLE_LAYOUT_SELECTOR = "TOGGLE_LAYOUT_SELECTOR";
export const TOGGLE_COMPONENT_SELECTOR = "TOGGLE_COMPONENT_SELECTOR";
export const TOGGLE_PROP_SELECTOR = "TOGGLE_PROP_SELECTOR";
export const ADD_COMPONENT_PROP = "ADD_COMPONENT_PROP";
export const UPDATE_COMPONENT_PROPS = "UPDATE_COMPONENT_PROPS";
export const UPDATE_COMPONENT_STYLE_CLASSES = "UPDATE_COMPONENT_STYLE_CLASSES";

export const TOGGLE_TOOLBOX_OPEN = "TOGGLE_TOOLBOX_OPEN";
export const MOVE_TOOLBOX = "MOVE_TOOLBOX";